### ISSUE TITLE
swatchseries.to

### ISSUE THREAD

**Issue by TiggenIt** [andrewjmetzger/better-watchseries#17]
It's now running this error when trying to load the page itself. This is the exact error it runs when I tried to load the site and it's been going on since yesterday.

"Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:

XID: 151113604"

**Comment by andrewjmetzger** [comment]
Hi @TiggenIt ! Unfortunately, it seems the domain `swatchseries.to` is dead. It redirects to `www1.watch-series.la`, which gives the 503 error you described. 

As indicated in the [README](https://github.com/andrewjmetzger/better-watchseries/blob/master/README.md#link-aggregators-watchseries), `swatchseries.to` is no longer a supported WatchSeries site. If you know of another WatchSeries type site,  I'd be happy to try adding support for it.
